/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GlobalStyle } from "./types";

export const DEFAULT_STYLE: GlobalStyle = {
  fontFamily: 'Montserrat',
  fontSize: 64,
  textColor: '#FFFFFF',
  fontWeight: '900',
  fontStyle: 'normal',
  textAlign: 'center',
  outlineEnabled: false,
  outlineColor: '#000000',
  outlineWidth: 3,
  shadowEnabled: true,
  shadowIntensity: 4,
  shadowColor: 'rgba(0,0,0,0.5)',
  backgroundEnabled: false,
  backgroundColor: '#000000',
  backgroundOpacity: 0.5,
  positionX: 50,
  positionY: 80,
  lineHeight: 1.2,
  letterSpacing: 0,
  casing: 'none',
  wordsPerSegment: 5,
  maxLines: 1,
  useOriginalSRT: false,
  aiAdaptiveLines: true,
  aiAdaptiveEmphasis: true,
  aiAdaptivePunctuation: false,
  animationEnabled: true,
  animationStyle: 'fade-in-word',
  highlightFontFamily: 'Montserrat',
  highlightFontSize: 68,
  highlightColor: '#FFD700', // Yellow premium
  highlightBoxColor: '#FFCC00', // Default active highlight box color
  glowEnabled: true,
  glowColor: '#FFD700',
  glowSize: 45,
  glowSpread: 3,
  adaptiveGlow: true,
  highlightBold: true,
  highlightItalic: false,
  aiEmphasis: false,
  aiLineFocusHighlighting: true,
  autoEmoji: false,
  randomRotate: false,
  fadeInDuration: 0.2,
  fadeOutDuration: 0.2,
  staggerDelay: 0.05,
  gScale: 1,
  gOpacity: 1,
  followUpStretch: true,
  followUpStretchAmount: 5,
  followUpStretchSpline: 'linear',
  canvasBackground: '#000000',
  popupIntensity: 1.0,
  popupMotionBlur: 0.1,
  popupDirection: 'center',
  highlightBoxPadding: 6,
  highlightBoxRadius: 4,
  aiSentimentColors: true,
  pitchModulation: true,
  kineticJitter: 1.0,
  emotionGlow: true,
  wordSpacing: 0,
  // Depth Captions defaults
  depthEnabled: false,
  depthIntensity: 100,
  depthSubjectOffsetX: 0,
  depthSubjectOffsetY: 0,
  depthSubjectMargin: 10,
  depthFontFamily: 'Bebas Neue',
  depthFontWeight: '900',
  depthFontColor: '#FF6F61', // Auralis theme!
  depthFontOpacity: 1.0,
  depthLetterSpacing: 2,
  depthLineHeight: 1.0,
  depthTextTransform: 'uppercase',
  depthBlurAmount: 0,
  depthGlowStrength: 0,
  depthGlowRadius: 10,
  depthShadowStrength: 0.5,
  depthShadowBlur: 15,
  depthOutlineWidth: 0,
  depthOutlineColor: '#000000',
  depthBigWordSize: 180, // Bold visual punch
  depthForegroundSize: 52,
  depthScaleAnimation: 1.1,
  depthPositionX: 50,
  depthPositionY: 50, // Screen center relative
  depthAutoCenter: true,
  depthSafeArea: 10,
  depthAnimationStyle: 'pop',
  depthAnimationDuration: 0.45,
  depthAnimationDelay: 0,
  depthAnimationEasing: 'spring',
  depthOpacityCurve: 'ease-in-out',
  depthScaleCurve: 'spring',
  onlyHighlightKeyword: false,
  depthMaskFeather: 3,
  depthModelSelection: 1,
  bionicReadingEnabled: false,
  bionicReadingStrength: 0.45,
  showSpeakerBadges: true,
};

export const FONT_FAMILIES = [
  'Atkinson Hyperlegible',
  'Lexend',
  'OpenDyslexic',
  'Inter', 
  'Bebas Neue',
  'Lilita One',
  'League Spartan',
  'Poppins',
  'Montserrat',
  'Outfit', 
  'Space Grotesk', 
  'Playfair Display', 
  'JetBrains Mono', 
  'GNF',
  'PIXELATED ELEGANCE',
  'Anton',
  'Lato',
  'Roboto',
  'Open Sans',
  'Oswald',
  'Raleway',
  'Nunito',
  'Rubik',
  'Bungee',
  'Alfa Slab One',
  'Syne',
  'Kanit',
  'Lobster',
  'Pacifico',
  'Righteous',
  'Cinzel',
  'Work Sans',
  'DM Sans',
  'Quicksand',
  'Josefin Sans',
  'Heebo',
  'Ubuntu',
  'Fira Sans',
  'Archivo',
  'Merriweather',
  'Comfortaa',
  'Unbounded',
  'Libre Baskerville',
  'Cormorant Garamond'
];

export const COLORS = [
  '#FF6F61', // Auralis
  '#FFFFFF', // White
  '#000000', // Black
  '#FFD700', // Gold
  '#00FF00', // Neon Green
  '#00BFFF', // Deep Sky Blue
  '#FF00FF', // Magenta
];
